### ISSUE TITLE
Add working-directory input

### ISSUE THREAD

**Issue by Jtalk** [matankdr/github-docker-sbt#2]
First of all, great project, very helpful, esp the docker support, thank you!

It'd be great to support setting a custom working directory for the `command` to be run in. I've spent about an hour making `cd subproject/ && sbt test ...` work, and had to settle on `eval`ing everything, which is not ideal. 

I think it'd get much easier if it could do something like this:
```yaml
    - name: Build & publish the project
      uses: matankdr/github-docker-sbt
      with:
        command: sbt test docker:publishLocal
        working-directory: projectname-ap # here we go
```
